import { v4 as uuidv4 } from 'uuid';
import type { Outline, NodeMap, OutlineNode } from '@/types';
import { calculateNodePrefix } from './outline-utils';

function createNode(
  nodes: NodeMap,
  id: string,
  parentId: string | null,
  name: string,
  content: string,
  childrenIds: string[] = []
): void {
  const type = childrenIds.length > 0 ? 'chapter' : 'document';
  const node: OutlineNode = { id, parentId, name, type, content, childrenIds, isCollapsed: false, prefix: '' };
  nodes[id] = node;

  if (parentId) {
      nodes[parentId].childrenIds.push(id);
  }
}

function createGuideNodes(): { rootNodeId: string, nodes: NodeMap } {
  const nodes: NodeMap = {};

  const rootId = 'guide-root';
  createNode(nodes, rootId, null, "IdiamPro User Guide", `Welcome to IdiamPro - an AI-native outlining platform that transforms scattered information into structured, actionable knowledge.

**What Makes IdiamPro Different**

Unlike traditional note-taking apps, IdiamPro combines hierarchical outlining with powerful AI synthesis. Import content from multiple sources - YouTube videos, PDFs, web pages, audio recordings, documents - and let AI find connections, identify themes, and create unified outlines automatically.

**Key Workflow Applications**

HIGH IMPACT:
• Meeting & Interview Synthesis - Record conversations, transcribe with speaker identification, get structured notes. Merge multiple meetings into a unified knowledge base.
• Video Course Note-Taking - Import YouTube lectures, get structured outlines automatically. Combine multiple videos on the same topic into comprehensive study guides.
• Research Aggregation - Import multiple PDFs, articles, and videos. AI finds connections across sources and creates unified research documents.
• Competitive Intelligence - Ingest competitor websites, product videos, press releases. Synthesize into strategic overviews.

PROFESSIONAL APPLICATIONS:
• Legal Discovery & Case Prep - Import depositions, documents, evidence into structured case outlines.
• Content Repurposing - Turn podcasts and videos into written outlines for blogs, courses, or books.
• Onboarding Documentation - Merge existing docs, wikis, and recorded tribal knowledge into structured guides.
• Client Project Briefs - Combine emails, calls, and reference materials into unified project scopes.

SPECIALIZED USES:
• Investment Analysis - Earnings calls, SEC filings, news articles synthesized into investment theses.
• Book/Thesis Writing - Import research sources, interviews, prior drafts into structured outlines.
• Event Planning - Vendor proposals, venue info, stakeholder requirements unified into event plans.

**Getting Started**

Click any item in the outline pane (left) to see details in the content pane (right). Use the Research & Import button (upload icon) to bring in external content. All your work saves automatically.

This guide cannot be deleted, but you can copy it to create your own customized version.`, []);

  // === GETTING STARTED ===
  const gettingStartedId = uuidv4();
  const autoSaveId = uuidv4();
  const toolbarId = uuidv4();

  createNode(nodes, gettingStartedId, rootId, "Getting Started", "IdiamPro helps you organize your thoughts into structured outlines. The interface has two main areas: the outline pane on the left shows your hierarchical structure, and the content pane on the right lets you edit the selected node's content. Everything saves automatically to your browser - just start working and your changes are preserved.", []);
  createNode(nodes, autoSaveId, gettingStartedId, "Auto-Save", "All changes are saved automatically to your browser's storage. No save button needed - your work is always preserved. Just refresh the page to confirm your outline persists.");
  createNode(nodes, toolbarId, gettingStartedId, "Toolbar Icons", "The toolbar uses icon buttons with hover tooltips and is responsive — fewer buttons show on narrow screens, with the rest tucked into a \"More tools\" overflow menu (the three-dot icon) so nothing is ever truly hidden.\n\n**Always visible (every screen size):**\n- Sidebar toggle (leftmost) — open or close the outline list\n- Outline title\n- Ask AI (chat-bubble) — opens the natural-language command bar\n- Plus, Delete, Search (action row) — node basics + search current outline\n- Account avatar (rightmost)\n\n**Phone (narrow): only the essentials show inline.** Everything else — Import, Export, Focus Mode, Show or hide all, Share subtree, Command palette, Second Brain, Smart Tools, Settings, Help, Refresh User Guide — moves into the \"More tools\" overflow menu (three-dot icon to the left of the avatar).\n\n**Tablet (medium): essentials plus the common dropdowns.** Inline you also see Import, Export, Focus Mode, Show or hide all, Share subtree, Command palette, Second Brain, Smart Tools. The overflow menu still appears, holding Settings, Help, and Refresh User Guide.\n\n**Desktop (wide): every icon is inline.** The overflow menu disappears because there's room for the full toolbar.\n\nThe overflow icon (three horizontal dots) lives just to the left of the account avatar so it's always in the same on-screen location. Keyboard shortcuts (Cmd+K, Cmd+F, Cmd+E, Cmd+Shift+E, Cmd+Shift+F, Cmd+Shift+I) keep working everywhere, regardless of whether the matching button is inline or in the overflow menu.");

  // === MANAGING OUTLINES ===
  const manageId = uuidv4();
  const createNewId = uuidv4();
  const switchId = uuidv4();
  const renameOutlineId = uuidv4();
  const deleteOutlineId = uuidv4();
  const importExportId = uuidv4();
  const autoBackupId = uuidv4();
  const autoUpdateId = uuidv4();

  createNode(nodes, manageId, rootId, "Managing Outlines", "IdiamPro supports multiple outlines, each stored separately. The sidebar (open it with the panel-toggle button at the top-left of the toolbar) is the home for switching, creating, renaming, and deleting outlines. The toolbar shows the current outline's name as a read-only title, plus three small icon buttons grouped together: an **Import** button (down-arrow book), an **Export** button (up-arrow book), and a **wrench** for residual admin actions (Refresh User Guide). The guide outline is special — it's restored automatically and cannot be deleted or renamed.", []);
  createNode(nodes, createNewId, manageId, "Creating a New Outline", "Open the sidebar (panel toggle at the top-left of the toolbar) and click 'New Outline' in Quick Actions. A new untitled outline is created and becomes your active outline. It starts with just a root node — add children to build your structure.");
  createNode(nodes, switchId, manageId, "Switching Outlines", "Open the sidebar to see all your outlines. Click any outline name to switch to it. Use the search field in the sidebar to find an outline by name. The app remembers which outline you were working on.");
  createNode(nodes, renameOutlineId, manageId, "Renaming an Outline", "Two ways to rename:\n\n1. In the sidebar, hover over an outline (or tap the ⋯ icon on mobile) and choose 'Rename'. Right-click also works on desktop.\n\n2. Double-click the root node name in the outline to edit it — this updates both the node and outline name.");
  createNode(nodes, deleteOutlineId, manageId, "Deleting an Outline", "In the sidebar, hover over an outline (or tap the ⋯ icon on mobile) and choose 'Delete'. You can also multi-select outlines in the sidebar and delete them in one step. A confirmation dialog appears before deletion. You cannot delete the guide outline or your last remaining outline — the app always keeps at least one user outline.");
  // Import/Export now has child nodes for detailed format documentation
  const exportFormatsId = uuidv4();
  const importFormatsId = uuidv4();

  createNode(nodes, importExportId, manageId, "Import/Export", "IdiamPro supports importing and exporting outlines in many formats, making it easy to share your work and bring in content from other applications. Both surfaces live in the top toolbar as dedicated icon buttons (down-arrow book = Import, up-arrow book = Export), each opening a small menu.\n\n**Import menu (BookDown icon):**\n• **Research & Import** — merge multiple sources (YouTube, PDFs, web pages, audio, etc.) into the current outline. AI synthesizes everything together.\n• **Import Outline** — bring in a single outline file (Markdown, Plain Text, OPML, JSON/.idm). Drag-and-drop or browse.\n• **Restore All Outlines** — pull any outlines stored in your folder back into the sidebar.\n\n**Export menu (BookUp icon):**\n• **Share Subtree as…** — exports just the currently-selected node and its descendants. Pick the format in the dialog. (This is also available by right-clicking any node — same action, different surface.)\n• **Export Current Outline** — exports the whole active outline.\n• **Backup All Outlines** — save every outline to disk in one shot.\n\nThe Share Subtree item disables when no node is selected.", []);

  createNode(nodes, exportFormatsId, importExportId, "Export Formats", "**DOCUMENTS**\n• **PDF** — Formatted document with headings. Best for: Sharing, printing, archiving.\n• **Markdown** — Headings (# ## ###) with content. Best for: GitHub, blogs, static sites, other markdown apps.\n• **Plain Text** — Indented outline structure. Best for: Universal compatibility, simple sharing.\n• **HTML** — Self-contained webpage with collapsible sections. Best for: Web sharing, interactive viewing.\n• **Interactive Outline** — Read-only outline viewer with sidebar tree navigation and content pane, styled like IdiamPro. Best for: Sharing outlines as browsable documents. Includes search, collapse/expand, dark/light mode, and mobile support.\n• **Website** — Professional website with hero, navigation, and sections. Choose from 8 templates: Marketing, Informational, Documentation, Portfolio, Event, Educational, Blog, and Personal. See the Website Generation section of this guide for details on each template.\n\n**OUTLINERS**\n• **OPML** — Standard outline interchange format. Best for: Moving between outliner apps (OmniOutliner, Workflowy, etc).\n• **JSON** — IdiamPro native format. Best for: Backup, transferring between devices.\n\n**NOTE APPS**\n• **Obsidian** — Markdown with [[wiki-links]] and YAML frontmatter. Best for: Obsidian vaults.\n\n**DATA**\n• **CSV** — Flattened table (Level, Prefix, Name, Path, Content). Best for: Spreadsheets, data analysis.\n• **JSON Tree** — Clean hierarchical JSON. Best for: APIs, programmatic access.");

  createNode(nodes, importFormatsId, importExportId, "Import Formats", "**DOCUMENTS**\n• **Markdown (.md)** — Parses heading hierarchy (# ## ###) into outline structure.\n• **Plain Text (.txt)** — Auto-detects indentation (tabs or spaces) and creates hierarchy.\n\n**OUTLINERS**\n• **OPML (.opml)** — Standard outline XML format from other outliners.\n• **JSON (.json, .idm)** — IdiamPro native format.\n\n**Importing Tips:**\n- File format is auto-detected from extension\n- You can override the outline name during import\n- Import shows stats: nodes imported, hierarchy depth\n- Warnings appear if the file has issues (empty, malformed, etc)");
  createNode(nodes, autoBackupId, manageId, "Automatic Backups", "On the desktop (Electron) app, IdiamPro automatically creates timestamped backups every time you save an outline.\n\n**How it works:**\n- A backup copy is saved to the 'backups' folder inside your outlines directory\n- Backups are named like: MyOutline_backup_2026-01-31T04-38-12.idm\n- Backups are throttled to at most one every 5 minutes per outline, so rapid edits don't flood your disk\n- The last 10 backups per outline are kept; older ones are automatically pruned\n\n**Recovery:**\nIf you need to recover a previous version, open Finder and navigate to your outlines folder > backups. Find the backup file with the timestamp you want and rename it to replace the original .idm file (remove the _backup_timestamp part).\n\n**Note:** Automatic backups are only available in the desktop Electron app. The web version relies on browser storage.");
  createNode(nodes, autoUpdateId, manageId, "Automatic Updates (Desktop)", "The desktop (Electron) app keeps itself up to date automatically. You don't have to download a new version manually.\n\n**How it works:**\n- A few seconds after you launch the app, it quietly checks our update server for a newer version. While the app is open, it re-checks every 4 hours.\n- If a newer version is available, the app downloads it in the background while you keep working. No interruption, no progress dialog, no extra clicks.\n- When the download finishes, a thin banner appears at the very top of the app: 'Update ready. Version X.Y.Z is ready. Restart to apply.' Two buttons: **Restart now** (apply right away) and **Later** (snooze for 24 hours, or until the next launch).\n- Picking **Later** is always safe — the banner will reappear after the snooze window, and the update is already on disk waiting to be applied.\n\n**Manual check:**\nIf you want to check on demand, use the Help menu > 'Check for Updates…'. The app reports back with a short toast — either 'You're on the latest version' or, if an update is available, the silent-download path kicks in just like the automatic check.\n\n**What you don't have to do:**\nDownload DMG files, drag the app to Applications, restart your Mac, or worry about whether your version is current. The desktop app handles all of that.\n\n**Note:** Automatic updates apply only to the desktop (Electron) build. On the web, the latest version is whatever loads when you refresh the page. On iOS, iPhone/iPad handles updates through the App Store / TestFlight as usual.");

  // === WEBSITE GENERATION ===
  const websiteGenId = uuidv4();
  const websiteGettingStartedId = uuidv4();
  const websiteTemplatesId = uuidv4();
  const websiteStructureId = uuidv4();
  const websiteCustomizationId = uuidv4();
  const websiteTipsId = uuidv4();

  createNode(nodes, websiteGenId, rootId, "Website Generation", "Turn any outline or subtree into a professional, self-contained website with one click. IdiamPro offers 8 website templates, each designed for a different purpose. Your outline's structure directly drives the website layout — top-level sections become website sections, and their children become cards, list items, and subsections.\n\nAccess website generation via the Share button in the toolbar (select a node first), then choose the Website format.", []);

  createNode(nodes, websiteGettingStartedId, websiteGenId, "Getting Started with Websites", "**How to generate a website:**\n\n1. Select any node in your outline (or the root node for the full outline)\n2. Click the Share button in the toolbar (square with arrow icon)\n3. Choose the **Website** format from the grid\n4. Pick a template that fits your content\n5. Set a title, tagline, and color scheme\n6. Choose your content depth (Overview, Standard, or Comprehensive)\n7. Click Generate to download a self-contained HTML file\n\n**What you get:**\nA single HTML file with all styles and scripts embedded. No server needed — open it in any browser, share it via email, or upload it to any web host.\n\n**Subtree vs. full outline:**\nSelect the root node to generate from your entire outline. Select any other node to generate from just that branch and its descendants.");

  createNode(nodes, websiteTemplatesId, websiteGenId, "Choosing a Template", "Each template transforms your outline into a different style of website. Choose based on your content's purpose:\n\n**Marketing** — Best for: Landing pages, product launches, book promotions.\nCreates a hero section with stats, benefits grid (from first 3 sections), chapter previews, FAQ section, and call-to-action. If you include a section named 'FAQ', it auto-generates a collapsible FAQ.\n\n**Informational** — Best for: Company pages, product info, corporate sites.\nClean Apple.com-inspired design with generous whitespace, key highlights, feature strips, and numbered topic cards.\n\n**Documentation** — Best for: User guides, API docs, reference manuals, wikis.\nIncludes a persistent sidebar with navigation, breadcrumbs, quick-start links, and previous/next page navigation. Sections are auto-grouped into chapters.\n\n**Portfolio** — Best for: Creative work, case studies, freelancer showcases.\nFilterable project grid with hover effects, featured work section, process/methodology steps, and contact CTA.\n\n**Blog** — Best for: Articles, news feeds, content hubs, knowledge bases.\nFeatured hero post, recent posts grid with reading time estimates, topic categories, newsletter signup form, and archive list.\n\n**Educational** — Best for: Courses, tutorials, training materials.\nCollapsible learning modules with numbered lessons (1.1, 1.2, etc.), auto-generated learning outcomes, progress indicators, and enrollment CTA.\n\n**Personal** — Best for: Resumes, CVs, professional profiles, about-me pages.\nExperience timeline, animated skills grid with proficiency bars, accomplishments stats, and contact section with social links.\n\n**Event** — Best for: Conferences, webinars, meetups, workshops.\nEvent hero with date/location info, schedule timeline, speaker/topic cards, highlights grid, and registration CTA.");

  createNode(nodes, websiteStructureId, websiteGenId, "Structuring Your Outline", "Your outline's structure directly determines how the website looks. Follow these guidelines for best results.\n\n**General Rules (all templates):**\n• Top-level children of the selected node become the main website sections\n• Their children become subsections, cards, or list items\n• Node names become section headings\n• Node content becomes body text and card descriptions\n• The first section often gets special treatment (hero subtitle, featured post, key benefit)\n• Aim for 4-8 top-level sections for the best visual balance\n\n**Template-Specific Tips:**\n\n• **Marketing:** Your first 3 sections become benefit cards. Add a section named 'FAQ' and it will auto-generate a collapsible FAQ section.\n\n• **Documentation:** Sections become sidebar navigation chapters. Order them from simple to advanced concepts. Subsections become documentation cards within each chapter.\n\n• **Portfolio:** Use top-level sections as categories (e.g., 'Web Design', 'Branding'). Add individual projects as children of each category.\n\n• **Blog:** Use top-level sections as topic categories. Add individual articles as children. The first article becomes the featured hero post.\n\n• **Educational:** Sections become learning modules. Add lessons as children — they'll be automatically numbered (1.1, 1.2, etc.). The first 6 sections auto-generate learning outcomes.\n\n• **Event:** Sections become schedule items on a timeline. Add speaker names and session details as subsections.\n\n• **Personal:** Sections 1-4 become your experience timeline entries. Sections 5+ become skill category cards with proficiency bars based on the number of sub-topics.\n\n• **Informational:** First 3 sections become key highlights. Keep content concise — the template emphasizes whitespace and typography.");

  createNode(nodes, websiteCustomizationId, websiteGenId, "Customization Options", "After choosing a template, you can customize the website's appearance:\n\n**Content Depth** — Controls how much of your outline content appears:\n• **Overview** — Section titles only with child names listed as bullets. Clean and minimal.\n• **Standard** — Includes the first paragraph of each section's content plus the full hierarchy of subsections.\n• **Comprehensive** — All content from every node rendered in a nested tree structure. Best for documentation.\n\n**Color Scheme:**\n• **Light** — White/light background\n• **Dark** — Dark background with light text\n• **Auto** — Matches the visitor's system preference\n\n**Custom Colors:**\n• **Primary** — Main accent color for buttons, links, and highlights\n• **Secondary** — Supporting color for borders and secondary elements\n• **Background** — Page background color\n• **Text** — Main text color\n\n**Title & Tagline:**\nThe title appears as the main heading in the hero section. The tagline appears below it as a subtitle.\n\n**CTA Button:**\nCustomize the call-to-action button text (e.g., 'Get Started', 'Learn More', 'Register Now').");

  createNode(nodes, websiteTipsId, websiteGenId, "Tips for Best Results", "**Write descriptive node names** — They become the section headings visitors see. 'Why This Matters' is better than 'Section 3'.\n\n**Add content to your nodes** — Templates extract the first paragraph for card summaries and descriptions. Empty nodes produce empty sections.\n\n**Use 4-8 top-level sections** — Fewer than 4 can look sparse. More than 8 can feel overwhelming. Most templates are optimized for this range.\n\n**Put your most important section first** — Many templates feature the first section prominently (as a hero, featured post, or key benefit).\n\n**Add subsections with content** — Children of your top sections render as feature cards, list items, and detail panels. The more structure you provide, the richer the website.\n\n**Try different templates** — The same outline can produce very different websites depending on the template. A project plan might work as Documentation, Marketing, or Event — try each to see what fits.\n\n**Match content depth to your template:**\n• Marketing and Event → Overview (clean, concise)\n• Blog and Personal → Standard (summaries + structure)\n• Documentation and Educational → Comprehensive (full content)\n\n**Iterate on your outline** — Generate a website, review it, then adjust your outline structure. Move sections, add content, rename nodes, and regenerate until it looks right.");

  // === WORKING WITH NODES ===
  const workingId = uuidv4();
  const addNodeId = uuidv4();
  const renameNodeId = uuidv4();
  const deleteNodeId = uuidv4();
  const selectNodeId = uuidv4();

  createNode(nodes, workingId, rootId, "Working with Nodes", "Nodes are the building blocks of your outline. Each node has a name (shown in the outline pane) and content (shown in the content pane when selected). Nodes can be nested to create hierarchical structures - a node with children becomes a 'chapter' while leaf nodes are 'documents'. The root node represents your entire outline and cannot be deleted.", []);
  createNode(nodes, addNodeId, workingId, "Adding Nodes", "Three ways to add nodes:\n\n1. Select a node, then click the + button\n2. Press Enter on a selected node to create a sibling below it\n3. Both methods create a sibling AFTER the selected node. If you select the root node, the new node becomes a child of root.");
  createNode(nodes, renameNodeId, workingId, "Renaming Nodes", "Double-click any node name to edit it. Press Enter to save, or Escape to cancel. You can also press Enter on a selected node to create a new sibling node beneath it. You can rename the root node too - this also updates the outline name.");
  createNode(nodes, deleteNodeId, workingId, "Deleting Nodes", "Three ways to delete a node:\n\n1. Select a node, then click the red trash icon\n2. Press Delete or Backspace key on a selected node\n3. Right-click > Delete from context menu\n\nA confirmation dialog appears (can be disabled in Settings). Deleting a node also deletes all its children. You cannot delete the root node.");
  createNode(nodes, selectNodeId, workingId, "Selecting Nodes", "Click any node to select it. The selected node is highlighted, and its content appears in the right pane for editing.");

  // Cross-outline link node (Phase 1, added 2026-06-04). A new node type that
  // points at another outline; clicking jumps you there.
  const outlineLinkNodeId = uuidv4();
  createNode(nodes, outlineLinkNodeId, workingId, "Link to Another Outline", "Insert a link node that points at another outline in your library. Clicking the link jumps you straight to the linked outline, and the linked outline also appears nested beneath the current one in the sidebar.\n\nHow to use:\n1. Open the Import menu in the toolbar (BookDown icon) and choose \"Link to Outline…\" — or right-click any node and pick \"Insert Link to Outline…\".\n2. Pick the target outline from the picker (the outline you're currently in is hidden so you can't accidentally link to yourself).\n3. A new link node is inserted as a child of the currently-selected node, or as a top-level child of the root if nothing is selected. Its name defaults to the linked outline's name; rename it freely.\n4. Click the link node any time to jump to that outline.\n\nA link node uses a distinctive arrow icon so it's easy to tell apart from regular nodes. If the linked outline gets deleted later, clicking the link tells you the outline is gone instead of breaking.\n\nSidebar nesting (Phase 2, 2026-06-04): once an outline links to another, the target shows up indented beneath the parent in the left sidebar. A small chevron on the parent row toggles the nested view; the open/closed state is remembered across sessions. The linked outline also stays at the top level of the sidebar so it's still easy to find on its own. If two different outlines both link to the same target, that target is shown nested under both — correctness over visual minimalism. Circular references (A links to B and B links back to A) are detected automatically: the second occurrence shows as a muted leaf with a small circular-arrow indicator and a tooltip explaining it's already shown above. Searching the sidebar matches names regardless of nesting depth.\n\nFuture phases will add inline previews of linked content; for now the link is click-to-navigate plus sidebar nesting.");

  // === ORGANIZING WITH DRAG & DROP ===
  const organizeId = uuidv4();
  const dragRulesId = uuidv4();
  const dropZonesId = uuidv4();
  const keyboardId = uuidv4();
  const visualFeedbackId = uuidv4();

  createNode(nodes, organizeId, rootId, "Organizing with Drag & Drop", "Restructure your outline by dragging nodes to new positions. Click and hold any node (except root) to drag it. As you drag over other nodes, visual indicators show where the node will be placed. You can also use keyboard shortcuts (Tab/Shift+Tab) to indent and outdent nodes quickly.", []);
  createNode(nodes, dragRulesId, organizeId, "Drag Rules", "- Any node except root can be dragged\n- Cannot drop a node onto itself\n- Cannot drop a parent into its own children (prevents loops)\n- Dropping onto root always places inside root");
  createNode(nodes, dropZonesId, organizeId, "Drop Zones", "When dragging over a node, three zones determine placement:\n\nTop 30% - Drop BEFORE (becomes previous sibling)\n\nMiddle 40% - Drop INSIDE (becomes child)\n\nBottom 30% - Drop AFTER (becomes next sibling)\n\nDropping inside a leaf node converts it to a chapter.");
  createNode(nodes, keyboardId, organizeId, "Keyboard Shortcuts", "Tab - Indent node (move inside previous sibling)\n\nShift+Tab - Outdent node (move after parent)\n\nDelete/Backspace - Delete selected node\n\nEnter - Create new sibling node\n\nThese only work when a node is selected and the action is valid.");
  createNode(nodes, visualFeedbackId, organizeId, "Visual Feedback", "While dragging:\n\n- Blue line shows before/after position\n- Dashed border shows inside (nesting) position\n- Dragged node becomes semi-transparent\n- Cursor changes to grab hand");

  const focusModeId = uuidv4();
  const searchFeaturesId = uuidv4();
  const expandCollapseAllId = uuidv4();
  const arrowNavId = uuidv4();
  const exportPdfId = uuidv4();

  createNode(nodes, focusModeId, organizeId, "Focus Mode", "Isolate a subtree to work without distraction.\n\nHow to use:\n1. Select any node\n2. Press Cmd+Shift+F to enter Focus Mode\n3. Only the selected node and its descendants are visible\n4. Press Esc to exit Focus Mode and return to the full outline\n\nFocus Mode is useful when working on one section of a large outline. All editing features work normally while focused.");

  createNode(nodes, searchFeaturesId, organizeId, "Search", "Find nodes across your outlines.\n\nHow to use:\n1. Press Cmd+F (Ctrl+F on Windows/Linux) to open the search panel\n2. Type your search query\n3. Results appear as you type\n\n**Search-as-view-shaper:**\nSearch doesn't just highlight — it reshapes the outline so only the matches and the chain of ancestors leading down to them stay expanded. Every other branch is automatically collapsed. No matter how huge or tangled the outline, you instantly see exactly the parts relevant to your query in their structural context.\n\n**Persistent state:**\nAfter you close the search panel (Escape or the X button), the tree stays in the search-shaped view — nothing snaps back. The outline only changes again when you do another search, click a chevron, run Expand All / Collapse All, or edit a node. This means you can search for a term, close the search bar, then continue working with the focused view.\n\n**Logical AND between searches (the funnel toggle):**\nThe funnel icon in the search bar toggles \"Search only open nodes.\" Turn it on, and the next search walks only the currently visible nodes — those left expanded by your previous search. This lets you chain queries to narrow results:\n1. Search \"alpha\" — tree shows alpha matches + their ancestors.\n2. Click the funnel icon to enable Search only open.\n3. Search \"beta\" — tree narrows to nodes that contain alpha AND beta.\n4. Repeat with more terms to drill down further.\n\nLeave the funnel off and every search starts fresh over the whole outline.\n\n**Scope Toggle (globe / page icon):**\n- Page icon — search the current outline only\n- Globe icon — search across all outlines\n\n**Search Filters:**\nTwo toggle buttons let you control what gets searched:\n- Outline icon — search node names/titles\n- T icon — search node content/body text\nBoth are on by default. Toggle either off to narrow your results. At least one must remain on.\n\n**Navigation:**\n- Use Prev/Next buttons to jump between results\n- Press Enter to step to the next match, Shift+Enter for the previous\n- Click any result to select that node");

  createNode(nodes, expandCollapseAllId, organizeId, "Expand All / Collapse All", "Open or close every descendant of a branch — all the way down to the leaves.\n\nHow to use:\n- Toolbar: a single icon button with bidirectional double-chevrons (pointing both down and up). The tooltip reads 'Show or hide all nodes'. Click it to open a dropdown with two items: 'Expand all' (top) and 'Collapse all' (below), each showing its keyboard shortcut.\n- Keyboard: Cmd+E (Expand All), Cmd+Shift+E (Collapse All) — these still fire directly without opening the menu.\n- Right-click a node: choose 'Expand All' or 'Collapse All' from the context menu.\n- Command Palette (Cmd+K): type 'Expand All' or 'Collapse All'.\n\nWhat counts as 'all':\n- If you have a node selected (or you right-clicked one), the action applies to THAT node's subtree only — everything below it.\n- If nothing is selected and you click the toolbar button or hit the shortcut, the action applies to the whole outline.\n\nDifference from the chevron next to a single node:\n- Clicking the chevron next to a single node toggles ONLY that node and remembers each descendant's previous open/closed state — when you reopen the branch later, it comes back looking the way you left it.\n- Expand All / Collapse All are explicit, recursive resets — they set EVERY descendant to the same state. After a Collapse All on a branch, reopening that branch shows only its immediate children (all of them collapsed), because every descendant was just collapsed.");

  createNode(nodes, arrowNavId, organizeId, "Arrow Key Navigation", "Navigate your outline quickly with arrow keys.\n\n- Up Arrow: Move selection to the previous visible node\n- Down Arrow: Move selection to the next visible node\n- Left Arrow: Collapse the selected node (if expanded) or move to parent\n- Right Arrow: Expand the selected node (if collapsed) or move to first child\n\nCombine with other shortcuts for fast editing: navigate with arrows, then press Enter to rename, Tab to indent, or Delete to remove.");

  createNode(nodes, exportPdfId, organizeId, "Export Subtree", "Export any node and its descendants in multiple formats.\n\nHow to use:\n1. Right-click any node\n2. Select 'Export Subtree...'\n3. The Export dialog opens with format options\n4. Choose a format (PDF, Markdown, HTML, OPML, etc.)\n5. Customize the filename and options\n6. Click Export\n\nAvailable formats include PDF, Markdown, HTML Website, Plain Text, OPML, Obsidian, CSV, and JSON Tree. Each format is useful for different purposes — see the Import/Export section under Managing Outlines for details.");

  // === AI FEATURES (Expanded) ===
  const aiId = uuidv4();
  const aiPlansId = uuidv4();
  const aiMenuId = uuidv4();
  const aiGenerateOutlineId = uuidv4();
  const aiGenerateContentId = uuidv4();
  const aiGenerateHowId = uuidv4();
  const aiGenerateContextId = uuidv4();
  const aiGenerateConflictId = uuidv4();
  const aiIngestId = uuidv4();
  const aiIngestSourcesId = uuidv4();
  const aiIngestPreviewId = uuidv4();
  const aiIngestMergeId = uuidv4();
  const aiImageGenId = uuidv4();
  const aiPodcastId = uuidv4();
  const aiLiveBooksId = uuidv4();
  const aiSafetyId = uuidv4();

  createNode(nodes, aiId, rootId, "AI Features", "IdiamPro includes powerful AI capabilities to help you generate content, create images, and build outlines faster. AI features are accessed through the violet sparkles icon and the image button in the toolbar.", []);

  // AI Plans
  createNode(nodes, aiPlansId, aiId, "AI Plans (FREE vs PREMIUM)", "IdiamPro offers two AI plans:\n\nFREE Plan:\n- AI content generation\n- External source ingestion\n- Standard AI processing\n\nPREMIUM Plan ($9.99/month):\n- All FREE features\n- AI image generation\n- Advanced AI model\n- Subtree summaries\n- Teach mode\n- Consistency checks\n- Priority processing\n- RAG-powered knowledge base (coming soon): Semantic search across all your outlines using vector embeddings for faster, more accurate cross-outline queries\n\nTo manage your plan: Click the AI menu (sparkles icon) > 'Manage AI Plan...'");

  // AI Menu
  createNode(nodes, aiMenuId, aiId, "Smart Tools menu", "Access intelligent features from a single menu:\n\n1. Click the sparkles icon in the toolbar — this is the Smart Tools menu (renamed 2026-06-04; previously \"AI Features\")\n2. The menu shows:\n   - Quick Command — type or speak any natural-language request (also ⌘K)\n   - Reformat with AI… — restructure a node's content (or a selection) per a plain-language instruction (\"turn into a bulleted list\", \"make each line a heading\")\n   - Generate Subtree from Topic — builds out a structured subtree under the selected node\n   - Translate this section — translate a subtree into another language\n   - Ask Your Outlines — search your outlines with natural language (previously \"Knowledge Chat\")\n\nResearch & Import has its own home in the toolbar's Import menu (BookDown icon), not the Smart Tools menu, so source-merging lives next to the other import actions. The Import menu also hosts \"Link to Outline…\" for inserting a cross-outline link node, and \"Refresh from Web\" (moved here 2026-06-06 — it brings external web content INTO existing nodes, so it fits the Import metaphor).\n\nYour current plan (Free or Premium) is shown in the menu header.");

  // Generate Outline from Topic
  createNode(nodes, aiGenerateOutlineId, aiId, "Generate Subtree from Topic", "Create a structured subtree from any topic under the selected node:\n\n1. Select a node in your outline\n2. Click AI menu > 'Generate Subtree from Topic'\n3. The topic field is pre-filled with the selected node's name — edit it if you want\n4. Choose depth, tone, and level settings\n5. Click 'Generate'\n6. AI creates a structured subtree as children of the selected node\n\nThis is great for building out sections of an existing outline. For example, select a node called 'Market Analysis', generate a subtree, and you'll get sub-sections like 'Competitor Landscape', 'Target Demographics', etc.");

  // Generate Content for Node
  createNode(nodes, aiGenerateContentId, aiId, "Generate Content for Node", "AI can write detailed content for any node in your outline.\n\nThe AI analyzes your node's title and its position in the hierarchy to generate relevant, contextual content. You control whether to replace existing content, append to it, or cancel.\n\nThe generation considers your outline structure from root to the selected node, ensuring thematic consistency.", []);
  createNode(nodes, aiGenerateHowId, aiGenerateContentId, "How to Trigger", "1. Select any node (except root)\n2. Click the violet sparkles button in the content pane header\n3. AI generates content based on the node's title and context");
  createNode(nodes, aiGenerateContextId, aiGenerateContentId, "Context & Input", "The AI uses:\n- The node's name/title\n- The path of ancestor nodes (for context)\n- Any existing content (as a draft to consider)\n\nThis helps AI generate relevant, contextual content that fits your outline structure.");
  createNode(nodes, aiGenerateConflictId, aiGenerateContentId, "Replace vs Append", "If the node already has content, you'll see options:\n\n- Replace: Overwrite existing content with AI content\n- Append Below: Add AI content after existing content\n- Cancel: Keep existing content unchanged\n\nYour content is never changed without your explicit choice.");

  // Research & Import (formerly Ingest External Source)
  createNode(nodes, aiIngestId, aiId, "Research & Import", "The Research & Import feature is the heart of IdiamPro's power. Import content from multiple sources simultaneously, and AI will synthesize them into a unified, structured outline.\n\n**Key Capabilities:**\n• Multi-source synthesis - Import multiple sources at once, AI finds connections\n• Smart defaults - YouTube titles, AI-generated names, automatic introductions\n• Merge or create new - Default merges into current outline, or create fresh\n• Speaker diarization - Audio recordings identify different speakers\n\n**Access:** Toolbar Import menu (BookDown icon) > 'Research & Import'. (Previously lived under the AI menu; moved 2026-06-04 so all import surfaces sit together.)", []);
  createNode(nodes, aiIngestSourcesId, aiIngestId, "Supported Sources", "**YouTube Videos**\n• Paste any YouTube URL\n• Transcript extracted automatically\n• Video title becomes default outline name\n\n**Conversation/Audio**\n• Paste transcript directly\n• Upload audio file for transcription\n• Record live with microphone\n• Speaker diarization identifies who said what\n\n**Documents**\n• PDF files (URL or upload)\n• Word, Excel, PowerPoint\n• Images with OCR text extraction\n\n**Other**\n• Web pages (URL)\n• Plain text/notes\n• Existing outline files (.idm)\n• Video files (audio extracted)");
  createNode(nodes, aiIngestPreviewId, aiIngestId, "Smart Naming & Summaries", "**Automatic Outline Naming:**\n• YouTube videos → Uses video title\n• Other sources → AI generates concise title from content\n• Fallback → Date-based name\n\n**Root Node Introduction:**\nWhen creating a new outline (not merging), the root node automatically gets an AI-generated introduction that summarizes all the content below it. This helps readers quickly understand the context.\n\n**Chapter Introductions:**\nParent/chapter nodes include introductory content that previews their children - no empty headers.");
  createNode(nodes, aiIngestMergeId, aiIngestId, "Merge vs New Outline", "**Default: Merge into Current Outline**\n• New content is synthesized with your existing outline\n• AI finds connections between old and new material\n• Preserves your existing structure\n• Content from both existing and new sources is integrated under shared themes\n\n**Option: Create New Outline**\n• Check 'Create new outline instead'\n• Provide a name or let AI generate one\n• Your current outline is unchanged\n\nThe merge behavior ensures you can continuously build knowledge on a topic from multiple sources over time.\n\n**Node Formatting:**\nResearch outlines use short names (2-6 words) as tree labels with detailed content in the content pane. Even in comprehensive mode, node names stay concise while all prose and detail goes into the content field.");

  // Pending Import Recovery
  const pendingImportId = uuidv4();
  createNode(nodes, pendingImportId, aiIngestId, "Pending Import Recovery", "On the desktop (Electron) app, if a Research & Import operation times out or the app closes during an import, the result is saved automatically.\n\nOn next launch:\n1. A recovery dialog appears\n2. It shows the pending import that was interrupted\n3. You can choose to apply the import or discard it\n\nThis ensures you never lose a long-running import due to network issues or accidental app closure.");

  // Undo Merge
  const undoMergeId = uuidv4();
  createNode(nodes, undoMergeId, aiIngestId, "Unmerge", "When merging research into an existing outline, a snapshot of your outline is taken before the merge begins.\n\nIf the merge produces bad results, look for the **Unmerge button** in the toolbar — it appears right after the Research & Import button as an orange circular arrow icon. Clicking it restores your outline to its exact pre-merge state.\n\nThe Unmerge button persists until you click it or perform another merge (which creates a new backup). You can freely edit the outline and still unmerge later. The backup survives app restarts. Only the most recent merge can be unmerged.");

  // AI Image Generation
  createNode(nodes, aiImageGenId, aiId, "AI Image Generation (Premium)", "Create custom illustrations with AI:\n\n1. Click the violet Image button in the content toolbar\n2. Describe the image you want (be specific about style, colors, composition)\n3. Choose an aspect ratio (square, landscape, portrait)\n4. Click 'Generate Image'\n\nThe AI-generated image is inserted directly into your content.\n\n**Tips for better results:**\n• Be specific: 'A serene mountain lake at sunset with purple sky' vs 'a lake'\n• Mention style: 'digital art', 'watercolor', 'photorealistic', 'minimalist'\n• Include composition details: 'close-up', 'wide angle', 'from above'\n\n**Note:** This feature requires a Premium plan.");

  // Generate Podcast
  createNode(nodes, aiPodcastId, aiId, "Generate Podcast", "Convert any subtree into a conversational audio podcast.\n\nHow to use:\n1. Right-click any node in the outline\n2. Select 'Generate Podcast'\n3. Configure your podcast:\n   • **Style**: Two-Host Discussion, Single Narrator, Interview, or Debate\n   • **Voices**: Choose from 6 OpenAI voices for each speaker\n   • **Length**: Brief (2-3 min), Standard (5-8 min), or Detailed (10-15 min)\n   • **Quality**: Standard (faster) or HD (higher quality)\n4. Click 'Generate' and wait for the AI to write the script and synthesize audio\n5. Preview the audio in the built-in player\n6. Click 'Save Audio File' to save the MP3\n\nThe script viewer lets you read along with the generated dialogue. You can also discard and regenerate with different settings.\n\nYour podcast preferences (style, voices, length, and audio quality) are remembered across sessions, so you don't need to reconfigure each time. When switching to a new style for the first time, your preferred voices carry over automatically.\n\n**Requirements:** Requires an OpenAI API key (OPENAI_API_KEY) in your environment for text-to-speech.");

  // Create Content for Descendants
  const aiDescendantsId = uuidv4();
  createNode(nodes, aiDescendantsId, aiId, "Create Content for Descendants", "Generate AI content for all child nodes of a parent at once.\n\nHow to use:\n1. Right-click a parent node (one that has children)\n2. Select 'Create Content for Descendants'\n3. AI generates content for every child node based on its title and context\n\nThis is a fast way to flesh out an entire section of your outline. Each child node receives content tailored to its title and position in the hierarchy. Existing content in child nodes is preserved - only empty nodes get new content.");

  createNode(nodes, aiLiveBooksId, aiId, "Refresh from Web", "Refresh from Web keeps your documents from going stale. It takes a node and everything under it, asks AI to refresh the content against the latest information on the internet, and shows you exactly what would change before anything is touched. (Internal code name: LIVE BOOKS — that name still appears in some technical files but not in the UI.)\n\nHow to use:\n1. Select the node you want to refresh (select the top/root node to refresh the whole outline)\n2. Open it one of three ways:\n   • Toolbar: Import menu (BookDown icon) > 'Refresh from Web' (moved here 2026-06-06 — it brings external web content INTO existing nodes, so it fits the Import metaphor)\n   • Command Palette (Cmd/Ctrl+K) > 'Refresh from Web'\n   • Keyboard: Cmd+Shift+R (Mac) / Ctrl+Shift+R (Windows/Linux)\n3. Choose how to update:\n   • Merge & augment (recommended) — keeps content that's still accurate, fixes what's outdated, folds in new developments\n   • Overwrite / regenerate — rewrites each section from scratch\n4. By default you get a side-by-side preview of every proposed change. Accept or reject each node individually, then click Apply. Nothing changes until you approve.\n5. (Optional) Tick 'Apply automatically without previewing' before running if you want changes applied directly — this is off by default and must be turned on deliberately each time.\n\nWhat it protects:\n• Nodes you edited by hand are automatically skipped so the refresh never clobbers your own writing. Skipped nodes are listed in the preview with an 'Include anyway' button if you want them refreshed too.\n\nSources & attribution:\n• Every refreshed node carries its sources. A small 'Sources' chip appears on the node — click it to see the citations and which AI model produced the refresh (e.g. 'Refreshed with Gemini 3.5 Flash'). Citations travel with the outline through save and export.\n• With cloud AI, refreshes use live web search and list the real pages used. With local AI (no internet), the refresh uses the model's built-in knowledge and clearly states that no web sources were available — it never invents citations.\n\nRefresh from Web is personal and local: it only changes your own copy of the outline after you approve.");

  // Translate (#52) — built on the same transform engine as LIVE BOOKS.
  const aiTranslateId = uuidv4();
  createNode(nodes, aiTranslateId, aiId, "Translate this section", "Translate any node and its descendants into another language, with the same preview-and-approve safety as Refresh from Web.\n\nBuilt for globally distributed teams (Boston ↔ Shanghai ↔ São Paulo): the language list is ordered so the most-requested global collaboration languages — Chinese (Simplified), Portuguese (Brazilian), Spanish, French, Japanese, Korean, German, Italian, Hindi — appear at the top.\n\nHow to use:\n1. Select the node you want to translate (select the top/root to translate the whole outline)\n2. Open it one of two ways:\n   • Toolbar: Smart Tools menu (sparkles icon) > 'Translate this section'\n   • Command Palette (Cmd/Ctrl+K) > 'Translate this section'\n3. Pick a target language from the dropdown (no default — you have to choose). Optionally tick 'Use local AI' to keep the translation entirely on your machine via Ollama.\n4. Click 'Translate & preview'. Each node's translation is shown side-by-side with the original. Reject any you don't want, then click 'Apply N translations'.\n\nFormatting (headings, lists, bold, links) is preserved. Proper nouns and code stay as-is. Nodes you edited by hand are auto-skipped with a per-node 'Include anyway' override, so translation never clobbers your edits.\n\nUsage: One Translate (regardless of how many nodes are in the subtree) counts as ONE generation against your monthly cap. Bring your own API key in Settings for unlimited use.");

  // Reformat with AI — single-shot per-node content reformat driven by a
  // plain-language instruction.
  const aiReformatId = uuidv4();
  createNode(nodes, aiReformatId, aiId, "Reformat with AI", "Reformat the content in a node by describing the format you want in plain English. Same workflow you'd use with an AI assistant for cleanup — built into the app.\n\nHow to open it:\n• Smart Tools menu (sparkles icon) > 'Reformat with AI…' — reformats the whole node\n• Right-click anywhere in the content area > 'Reformat with AI…' — reformats the whole node, or just your selection if text is selected\n• Select some text in the content editor — the floating formatting toolbar (bubble menu) shows a violet wand button at the LEFT END with a small 'Most Powerful' badge; click it to reformat just the selection (moved to first position 2026-06-05 to make it the eye-magnet of the toolbar)\n• Command Palette (Cmd/Ctrl+K) > 'Reformat with AI…'\n\nThe dialog:\n1. Type the format you want — e.g. 'turn into a bulleted list', 'make each line a heading', 'convert to a markdown table', 'tighten spacing and remove empty lines'.\n2. Or click one of the example chips below the input to fill it in.\n3. Click 'Preview reformat'. The AI returns a reformatted version, shown side-by-side with the original.\n4. Click 'Apply' to keep it, 'Modify instruction' to tweak and try again, or 'Cancel' to discard.\n\nWhat it preserves: Your actual words and meaning. Reformat changes structure and presentation — it doesn't invent new content or delete substance unless you explicitly ask it to summarise.\n\nOptional: Tick 'Use local AI (Ollama)' to run the reformat entirely on-device.\n\nUsage: One reformat = ONE generation against your monthly cap, regardless of how long the content is. Available on every tier (Free trial, Student, Pro) and free with your own API key.");

  // Discovery Hints — sticky "Did You Know?" tips that surface the first
  // time a new user hits a feature worth knowing about.
  const discoveryHintsId = uuidv4();
  createNode(nodes, discoveryHintsId, aiId, "Did You Know? tips", "SecondBrainWare surfaces sticky discovery cards in the lower-right corner the first time you reach a feature worth knowing about — short, conversational, one-tip-at-a-time.\n\n**Examples (v1):**\n• First text selection in the editor → 'Reformat with AI is here' tip (points at the violet wand at the left end of the bubble menu)\n• Six seconds later → 'Smart Tools = your AI toolkit' tip (points at the sparkle icon in the toolbar)\n• First time you create an outline → 'Link one outline to another' tip, then 10 seconds later an 'Import and Export live in the toolbar' tip\n• First time you open a BYOK key entry in Settings → 'Bring your own API key for unlimited use' tip\n\n**How they behave:**\n• Tips do NOT auto-dismiss — click the 'Got it' button when you've read it\n• Multiple tips stagger so they never pile up\n• Each tip has the eyebrow 'Did You Know?' and a violet sparkle so they're distinguishable from regular toasts\n\n**Two ways to dismiss (2026-06-05):**\nEvery 'Did You Know?' card has TWO controls along its bottom edge: a checkbox labelled 'Don't show me this again', and the 'Got it' button.\n• **Just click 'Got it'** (checkbox UNCHECKED): the card disappears for now, but the same tip is eligible to pop up again the next time the same thing happens (e.g. the next time you select text). Useful when you want the card out of the way but a refresher later would be welcome.\n• **Check the box, then click 'Got it'**: the tip goes onto a permanent 'never show again' list and won't appear for you ever again — not even if you later switch Professional mode off.\n\n**Professional mode (turn off all tips):**\nSettings → Tips → 'Professional mode' is the master switch. Turn it ON to suppress every tip — anything currently visible disappears and no new tips will fire. Turn it OFF to restore the normal new-user behaviour: tips will fire again on their triggers — except anything you marked 'Don't show me again', which stays hidden forever. A brief confirmation card titled 'Welcome tips re-enabled' confirms the switch.\n\nUsed correctly, the tips drop off after the first week and you only see them again if SecondBrainWare ships a meaningful new feature.");

  // Local AI / Ollama
  const aiOllamaId = uuidv4();
  createNode(nodes, aiOllamaId, aiId, "Local AI / Ollama", "Run AI features using a local model instead of cloud services.\n\nSetup:\n1. Install Ollama (ollama.ai) on your machine — version 0.20+ required for Gemma 4 support\n2. Pull a model: ollama pull gemma4:e4b (recommended for most users)\n3. In IdiamPro: Settings > AI Provider\n4. Choose 'Local (Ollama)' or 'Auto'\n\n**Provider Options:**\n- Cloud: Uses cloud AI (default)\n- Local (Ollama): Uses your local Ollama instance on localhost:11434\n- Auto: Tries local first, falls back to cloud if unavailable\n\n**Recommended Models (Gemma 4 — released April 2026):**\n- gemma4:e2b — Lightweight (~1.5GB RAM), mobile-friendly, multimodal\n- gemma4:e4b — RECOMMENDED (~4GB RAM), multimodal, best balance for most systems\n- gemma4:26b — High quality (~16GB RAM), Mixture of Experts, fast despite size\n- gemma4:31b — Maximum quality (~24GB RAM), beats Llama 4 on benchmarks\n\n**Legacy fallback:**\n- llama3.2 — For systems with less than 4GB RAM\n\nIdiamPro automatically selects the best model installed based on your system memory. Gemma 4 models support text + image (multimodal), enabling local image analysis without sending to cloud.\n\nLocal AI keeps your data on your machine and works offline.");

  // AI Data Consent
  const aiConsentId = uuidv4();
  createNode(nodes, aiConsentId, aiId, "AI Data Consent & Privacy", "IdiamPro requires your explicit consent before sending data to AI services.\n\n**First-time consent:**\nWhen you use any AI feature for the first time, a consent dialog appears explaining which services process your data:\n- **Google Gemini** — text generation, content expansion, outline creation\n- **OpenAI** — podcast audio synthesis (text-to-speech)\n- **AssemblyAI** — audio transcription\n\nYou must click 'I Agree' to enable AI features. If you decline, all non-AI features remain fully functional.\n\n**Managing consent:**\nGo to Settings > Data & Privacy to toggle AI data processing on or off at any time.\n\n**Privacy Policy:**\nAvailable at /privacy. Your outlines are stored locally on your device and are never uploaded for storage. Data is only sent to AI services when you explicitly invoke an AI feature.");

  // Safety & Control
  createNode(nodes, aiSafetyId, aiId, "Safety & Control", "You're always in control:\n\n- All AI content is fully editable - change or delete anything\n- Preview mode shows changes before they're applied\n- No automatic modifications to your content\n- Auto-save preserves all changes (including AI content)\n- Undo by using browser back or editing content\n\nAI is a tool to help you - the final decisions are always yours.");

  // Knowledge Chat
  const knowledgeChatId = uuidv4();
  const kcQueryId = uuidv4();
  const kcCurrentModeId = uuidv4();
  const kcAllModeId = uuidv4();
  const kcTipsId = uuidv4();

  createNode(nodes, knowledgeChatId, aiId, "Ask Your Outlines", "Query your outlines with natural language. Ask questions, find information, and discover connections across your content using AI. (Renamed 2026-06-04 — previously called \"Knowledge Chat\".)\n\n**Access:** Smart Tools menu > Ask Your Outlines, or use the 🧠 Second Brain menu > Search Second Brain.\n\n**Three Modes:**\n- Current Outline — queries only the active outline\n- All Outlines — queries all your outlines at once\n- 🧠 Second Brain — queries only your Second Brain outline\n\nThe AI answers based only on your outline content, referencing specific sections and making cross-outline connections.\n\n**Streaming Responses:** Answers appear word-by-word as they're generated, so you see the first words within 1-2 seconds instead of waiting for the full response.", []);

  createNode(nodes, kcQueryId, knowledgeChatId, "Querying Your Outlines", "How to use Ask Your Outlines:\n\n1. Click the brain icon (blue) in the toolbar\n2. The chat dialog opens with your current outline loaded\n3. Type a question in natural language\n4. The AI responds using information from your outlines\n\n**Example questions:**\n- 'What are the key findings from my research?'\n- 'Summarize the Q1 goals'\n- 'What connections exist between marketing and product?'\n- 'Find everything related to budget constraints'");

  createNode(nodes, kcCurrentModeId, knowledgeChatId, "Current Outline Mode", "Queries only the currently selected outline.\n\nBest for:\n- Focused questions about one topic\n- Finding specific details within a document\n- Working with very large outlines\n\nThe context info bar shows the outline name, node count, and estimated token usage.");

  createNode(nodes, kcAllModeId, knowledgeChatId, "Second Brain Mode (All Outlines)", "Queries all your outlines simultaneously.\n\nBest for:\n- Finding connections across different topics\n- Research synthesis — 'What do my sources say about X?'\n- Memory recall — 'Where did I write about Y?'\n- Cross-referencing information\n\n**Desktop (Electron):** Uses a pre-built knowledge base file that's automatically kept in sync when you save, rename, or delete outlines.\n\n**Web:** Serializes all in-memory outlines on the fly.\n\nThe context info bar shows how many outlines and nodes are included.");

  createNode(nodes, kcTipsId, knowledgeChatId, "Tips & Use Cases", "**Research Synthesis:**\nImport multiple sources with Research & Import, then use Ask Your Outlines to ask cross-cutting questions.\n\n**Memory Recall:**\nCan't remember where you wrote something? Ask 'Where did I mention...' in All Outlines mode.\n\n**Finding Connections:**\nAsk 'What connections exist between [topic A] and [topic B]?' to discover relationships you might have missed.\n\n**Token Limits:**\n- A warning appears if context exceeds 500K tokens\n- If it exceeds 1M tokens, switch to Current Outline mode\n- Most outlines are well within limits");

  // === SECOND BRAIN ===
  const secondBrainGuideId = uuidv4();
  const sbSaveId = uuidv4();
  const sbSearchId = uuidv4();
  const sbMenuId = uuidv4();
  const sbQuickCaptureId = uuidv4();
  const sbDashboardId = uuidv4();
  const sbAutoTagId = uuidv4();

  createNode(nodes, secondBrainGuideId, rootId, "Second Brain", "Your Second Brain is a special, always-present outline where you accumulate everything you want to remember — notes, research, ideas, articles, images, anything. It's your personal knowledge base, searchable by natural language via AI.\n\nThe Second Brain outline is created automatically when you first launch the app. It appears at the top of your outline list with a 🧠 icon and cannot be deleted or renamed.\n\nAll existing features work on it: import from any source, merge outlines into it, export in any format, expand content with AI. The difference is it's always there, always pinned, and has its own dedicated search mode.", []);

  createNode(nodes, sbSaveId, secondBrainGuideId, "Saving to Second Brain", "Save any node (and its entire subtree) to your Second Brain:\n\n**From the context menu:**\n1. Right-click any node in any outline\n2. Select '🧠 Save to Second Brain'\n3. The node and all its children are copied into your Second Brain\n\n**From the toolbar:**\n1. Select a node\n2. Click the 🧠 brain icon in the toolbar\n3. Select 'Save Selection to Second Brain'\n\n**Keyboard shortcut:** ⌘⇧B (Cmd+Shift+B)\n\nThe original node stays in place — a copy is added to the Second Brain.");

  createNode(nodes, sbSearchId, secondBrainGuideId, "Searching Your Second Brain", "Query your Second Brain with natural language:\n\n**From the toolbar:**\n1. Click the 🧠 brain icon\n2. Select 'Search Second Brain'\n3. Ask Your Outlines opens in Second Brain mode (green button)\n4. Ask any question — the AI searches only your Second Brain content\n\n**Keyboard shortcut:** ⌘⇧S (Cmd+Shift+S)\n\nYou can also open Ask Your Outlines from the Smart Tools menu and switch to the 🧠 Second Brain tab manually.\n\n**Example questions:**\n- 'What do I know about machine learning?'\n- 'Summarize my notes on the competitor analysis'\n- 'Find everything related to quarterly goals'");

  createNode(nodes, sbMenuId, secondBrainGuideId, "Second Brain Toolbar Menu", "The 🧠 brain icon in the toolbar gives you quick access to all Second Brain actions:\n\n- **Open Second Brain** — switches to the Second Brain outline (no shortcut: ⌘B is reserved for the sidebar)\n- **Quick Capture** (⌘⇧I) — drop a quick thought into your Inbox from anywhere\n- **Save Selection to Second Brain** (⌘⇧B) — copies selected node and subtree\n- **Search Second Brain** (⌘⇧S) — opens Ask Your Outlines in Second Brain mode\n- **View Dashboard** — overview of recent saves, revisit pile, and top tags\n- **Import to Second Brain** — switches to Second Brain and opens Research & Import");

  createNode(nodes, sbQuickCaptureId, secondBrainGuideId, "Quick Capture", "Drop any thought into your Second Brain from anywhere in the app — no need to navigate to an outline first.\n\n**How it works:**\n1. Press ⌘⇧I (Cmd+Shift+I) — a floating dialog appears\n2. Type or paste any text (a thought, a quote, a link, a reminder)\n3. Hit Enter or click \"Save to Inbox\"\n4. Your entry lands in a 📥 Inbox section at the top of your Second Brain\n\n**No keyboard? No problem.** Click the 🧠 brain icon in the toolbar and choose Quick Capture. The same dialog opens — works on iPad/iPhone where ⌘⇧I isn't available.\n\nThe Inbox is created automatically the first time you use Quick Capture. The first 60 characters become the node name; anything longer goes into the content pane.\n\n**Smart auto-tagging:** Right after saving, the AI suggests 1-3 short topical tags and applies them automatically. A toast tells you which tags were added.\n\nPerfect for friction-free capture during reading, meetings, or any moment when an idea hits.");

  createNode(nodes, sbDashboardId, secondBrainGuideId, "Second Brain Dashboard", "Get a bird's-eye view of your Second Brain — what you've saved, what to revisit, and what topics dominate.\n\n**Access:** 🧠 Brain menu > View Dashboard\n\n**What it shows:**\n- **Total entries** — how much you've accumulated overall\n- **Recent saves (last 7 days)** — what you've added this week\n- **Revisit pile** — older entries the AI nudges you to revisit so they don't get buried\n- **Top tags** — your most common topics, useful for spotting themes\n\nClick any entry in the dashboard to jump straight to that node in your Second Brain.");

  createNode(nodes, sbAutoTagId, secondBrainGuideId, "Smart Auto-Tagging", "Every time you save something to your Second Brain — via Quick Capture, Save Selection, or Import — the AI automatically suggests 1-3 short topical tags and applies them to the new node.\n\n**Why tags matter:**\n- Tags are stored as node metadata and shown in the Dashboard's \"Top tags\" section\n- Helps the AI find related material when you search\n- Makes the Revisit pile more meaningful — you can see at a glance what each item is about\n\n**Adjusting tags:** Tags are non-blocking — your save always succeeds first, then tags arrive a moment later. You can edit them anytime via the existing tag UI on the node.\n\nTags are short, lowercase, hyphenated (e.g. `machine-learning`, `quarterly-goals`).");

  // === IMPORTING MEDIA ===
  const mediaId = uuidv4();
  const photoId = uuidv4();
  const videoId = uuidv4();
  const youtubeId = uuidv4();
  const audioId = uuidv4();
  const pdfId = uuidv4();
  const drawingId = uuidv4();
  const fullscreenId = uuidv4();

  createNode(nodes, mediaId, rootId, "Importing Media", "Add photos, videos, audio, PDFs, and other files to your content using the Import File button (paperclip icon) in the toolbar, or by dragging files directly into the content pane. The file type is auto-detected: images embed as viewable photos, videos embed with playback controls, audio files embed with a native audio player, PDFs offer a choice to extract text or insert as a download link, and other files are inserted as download links. Media is saved with your outline.", []);
  createNode(nodes, photoId, mediaId, "Photos & Images", "Insert images from your device:\n\n1. Click the Import File button (paperclip icon) in the toolbar\n2. Choose an image file (JPEG, PNG, etc.)\n\nOr simply drag and drop an image file into the content pane.\n\nYou can also **paste images directly from your clipboard** (Cmd+V / Ctrl+V). This works with screenshots, images copied from websites, or any image on your clipboard.\n\nImages are stored directly in your outline - no external hosting needed.");
  createNode(nodes, videoId, mediaId, "Video Files", "Insert video files from your device:\n\n1. Click the Import File button (paperclip icon) in the toolbar\n2. Choose a video file (MP4, MOV, etc.)\n\nVideos include full playback controls (play, pause, seek, volume). Note: Large videos increase outline file size.");
  createNode(nodes, audioId, mediaId, "Audio Files", "Insert audio files from your device:\n\n1. Click the Import File button (paperclip icon) in the toolbar\n2. Choose an audio file (MP3, WAV, AAC, etc.)\n\nAudio files embed with a native audio player that includes play, pause, seek, and volume controls. You can also drag and drop audio files or paste them from your clipboard.");
  createNode(nodes, youtubeId, mediaId, "YouTube Videos", "Embed YouTube videos that stream directly:\n\n1. Click the + (Insert) menu > 'YouTube Video'\n2. Paste any YouTube URL\n3. The video embeds with full playback controls\n\nYouTube videos stream from YouTube's servers - they don't increase your outline size.");
  createNode(nodes, pdfId, mediaId, "PDF Documents", "Import PDF files from your device:\n\n1. Click the Import File button (paperclip icon) in the toolbar\n2. Choose a PDF file\n3. A dialog appears with two options:\n   - **Extract Document**: Uses AI to extract and format the PDF content with preserved headings, lists, and structure\n   - **Insert as Link**: Inserts a clickable download link for the PDF\n\nYou can also drag and drop PDF files into the content pane.");
  createNode(nodes, drawingId, mediaId, "Drawings & Sketches", "Create freehand drawings:\n\n1. Click the + (Insert) menu > 'Drawing'\n2. Use the drawing canvas to sketch\n3. Click 'Insert' to add to your content\n\nDrawings are saved as images in your outline.");
  createNode(nodes, fullscreenId, mediaId, "Fullscreen Viewing", "Double-click any image, video, or diagram to view it fullscreen. This is especially useful for:\n\n- Reading details in photos\n- Viewing diagrams at full size\n- Watching videos without distraction\n\nClick outside the content or press the X button to close fullscreen view.");

  const richTextId = uuidv4();
  const googleDocsId = uuidv4();
  const googleSheetsId = uuidv4();
  const googleSlidesId = uuidv4();
  const googleMapsId = uuidv4();
  const speechToTextId = uuidv4();

  createNode(nodes, richTextId, mediaId, "Rich Text Formatting", "The content editor supports full rich text formatting:\n\n**Text Styling:**\n- Bold: Cmd+B (Ctrl+B on Windows)\n- Italic: Cmd+I (Ctrl+I on Windows)\n- Strikethrough\n\n**Headings:**\n- H1, H2, H3 heading levels\n\n**Lists:**\n- Ordered (numbered) lists\n- Unordered (bullet) lists\n- Checklist (task) lists with checkboxes\n\n**Code:**\n- Code blocks with syntax formatting\n\n**Undo/Redo:**\n- Undo: Cmd+Z (Ctrl+Z)\n- Redo: Cmd+Shift+Z (Ctrl+Shift+Z)\n\nAll formatting is preserved when you switch between nodes or close the app.\n\n**Touch-Accessible Toolbar (works on iPhone, iPad, and desktop):**\n- The content pane toolbar now includes **Undo** and **Redo** buttons at the left end, plus **Bullet List**, **Numbered List**, and **Checklist** buttons. These give you one-tap access to the most common editor actions without needing a keyboard or a right-click context menu.\n- **Floating formatting toolbar** — select any text in the editor and a small floating menu appears above the selection with Bold, Italic, Strikethrough, Inline Code, and Heading 1/2/3 buttons. Active formatting is highlighted so you can see what's already applied. This works on both desktop and touch devices.\n\n**Links:**\nPaste URLs from your clipboard and they automatically become clickable links. Links from rich HTML (e.g. copied from ChatGPT or web pages) are also preserved. Links open in a new tab when clicked.");

  createNode(nodes, googleDocsId, mediaId, "Google Docs Embedding", "Embed Google Docs directly in your content:\n\n1. Click the + (Insert) menu in the content toolbar\n2. Paste a Google Docs URL\n3. The document renders as an inline preview\n\nThe embedded doc displays within your content pane. The document must be publicly shared or shared with you.");

  createNode(nodes, googleSheetsId, mediaId, "Google Sheets Embedding", "Embed Google Sheets directly in your content:\n\n1. Click the + (Insert) menu in the content toolbar\n2. Paste a Google Sheets URL\n3. The spreadsheet renders as an inline preview\n\nUseful for referencing live data, shared budgets, or tracking sheets within your outline.");

  createNode(nodes, googleSlidesId, mediaId, "Google Slides Embedding", "Embed Google Slides presentations directly in your content:\n\n1. Click the + (Insert) menu in the content toolbar\n2. Paste a Google Slides URL\n3. The presentation renders as an inline preview\n\nGreat for referencing presentations alongside your outline notes.");

  createNode(nodes, googleMapsId, mediaId, "Google Maps Embedding", "Embed Google Maps directly in your content:\n\n1. Click the + (Insert) menu in the content toolbar\n2. Paste a Google Maps URL\n3. The map renders as an inline preview\n\nUseful for event planning, travel outlines, or location-based research.");

  createNode(nodes, speechToTextId, mediaId, "Speech-to-Text", "Record audio and have it transcribed to text directly in the content pane.\n\nHow to use:\n1. Click the microphone button in the content toolbar\n2. Speak into your microphone\n3. Your speech is transcribed to text in real time via the Web Speech API\n\nNote: Requires browser microphone permission. Works best in Chrome and Edge. Transcription happens locally in your browser - no audio is sent to external servers.");

  // === ADVANCED NODE FEATURES ===
  const advancedId = uuidv4();
  const nodeTypesId = uuidv4();
  const taskNodesId = uuidv4();
  const linkNodesId = uuidv4();
  const codeNodesId = uuidv4();
  const quoteNodesId = uuidv4();
  const dateNodesId = uuidv4();
  const tagsId = uuidv4();
  const colorsId = uuidv4();
  const nodeInteractionsId = uuidv4();

  createNode(nodes, advancedId, rootId, "Advanced Node Features", "IdiamPro supports specialized node types and organization tools like tags and colors. These features help you create more structured and visually organized outlines.", []);

  createNode(nodes, nodeTypesId, advancedId, "Node Types", "Beyond standard document and chapter nodes, IdiamPro supports several specialized node types, each with unique editors and functionality. Access these by right-clicking a node and selecting 'Set Type' from the context menu.", []);

  createNode(nodes, taskNodesId, nodeTypesId, "Task/Checklist Nodes", "Task nodes display a checkbox that you can click to mark items as complete. Completed tasks show strikethrough text.\n\nFeatures:\n- Click the checkbox to toggle completion\n- Completed tasks are visually distinguished\n- Perfect for to-do lists and action items\n- Can still have full rich text content");

  createNode(nodes, linkNodesId, nodeTypesId, "Link/Bookmark Nodes", "Link nodes store URLs and provide quick access to external resources.\n\nFeatures:\n- URL input field in the content pane\n- 'Open Link' button to visit the URL\n- Click the node name to open in new tab\n- Blue underlined styling indicates it's a link\n- Store notes about the link in the content area");

  createNode(nodes, codeNodesId, nodeTypesId, "Code Snippet Nodes", "Code nodes provide syntax-highlighted code editing with support for 13+ programming languages.\n\nFeatures:\n- Language selector (JavaScript, Python, TypeScript, Java, C#, PHP, Ruby, Go, Rust, SQL, JSON, CSS, HTML)\n- Syntax highlighting with Prism.js\n- Monospace font\n- Copy button for quick code copying\n- Great for documentation and code examples");

  createNode(nodes, quoteNodesId, nodeTypesId, "Quote/Citation Nodes", "Quote nodes are designed for storing quotations with proper attribution.\n\nFeatures:\n- Dedicated quote text area with italic styling\n- Source/attribution field for crediting\n- Purple left border for visual distinction\n- Blockquote formatting\n- Perfect for research and references");

  createNode(nodes, dateNodesId, nodeTypesId, "Date/Event Nodes", "Date nodes help you track important dates and events.\n\nFeatures:\n- Date picker interface\n- Formatted date display (e.g., 'Monday, January 5, 2026')\n- Store notes about the event\n- Orange icon for visibility\n- Useful for timelines and planning");

  const canvasNodesId = uuidv4();
  const spreadsheetNodesId = uuidv4();

  createNode(nodes, canvasNodesId, nodeTypesId, "Canvas/Drawing Nodes", "Canvas nodes provide a full freeform drawing surface powered by Excalidraw.\n\nHow to use:\n1. Right-click a node > 'Set Type' > 'Canvas'\n2. The content pane becomes a drawing canvas\n3. Use the drawing tools to sketch, diagram, or annotate\n\nFeatures:\n- Full Excalidraw drawing tools (shapes, arrows, text, freehand)\n- Dark mode support\n- Saves as image data within your outline\n- Great for diagrams, flowcharts, wireframes, and visual notes");

  createNode(nodes, spreadsheetNodesId, nodeTypesId, "Spreadsheet Nodes", "Spreadsheet nodes embed a full spreadsheet editor powered by Fortune Sheet.\n\nHow to use:\n1. Right-click a node > 'Set Type' > 'Spreadsheet'\n2. The content pane becomes a spreadsheet grid\n3. Edit cells, enter formulas, and organize data\n\nFeatures:\n- 50 rows × 26 columns (A-Z)\n- Full cell editing with formulas\n- Data persists with your outline\n- Useful for budgets, tables, comparisons, and structured data");

  createNode(nodes, tagsId, advancedId, "Tags", "Organize nodes with colored tags. Tags help you categorize and filter content across your outline.\n\nFeatures:\n- Add multiple tags to any node\n- Colored badges appear next to node names\n- Click 'x' on a badge to remove a tag\n- Tag Manager dialog for managing all tags\n- Each tag automatically gets a distinct color\n- Future: Filter outline by tags");

  createNode(nodes, colorsId, advancedId, "Node Colors", "Add visual distinction to nodes with custom colors displayed as a left border.\n\nHow to use:\n- Right-click any node > 'Set Color'\n- Choose from 8 colors + default\n- 4px colored left border appears on the node\n- Great for prioritizing or categorizing\n- Works alongside chapter colors\n\nColors: Red, Orange, Yellow, Green, Blue, Purple, Pink");

  createNode(nodes, nodeInteractionsId, advancedId, "Node Interactions", "How to interact with nodes on desktop and mobile.\n\n**Selecting a node:**\n- Desktop: Click the node\n- Mobile: Tap the node\n\n**Renaming a node:**\n- Desktop: Double-click the node, or select it and press Enter\n- Mobile: Tap the already-selected node again\n\n**Multi-select (selecting many nodes for bulk operations):**\n- Desktop: Cmd/Ctrl+Click to toggle a node in the selection, Shift+Click to select a range\n- Mobile: Long-press any node (~half a second, don't move your finger) to enter multi-select mode — the long-pressed node becomes the first selection, then plain taps on other nodes toggle them in or out\n- A blue ring shows which nodes are selected. The multi-select toolbar appears at the bottom with bulk actions (color, tag, indent/outdent, delete).\n- Press Escape (desktop) or tap the Cancel button in the toolbar to exit multi-select mode.\n\n**Focus Mode:**\n- Select a node, then click the Focus button in the toolbar (target icon) or press Cmd+Shift+F\n- Only the selected node and its descendants are shown — everything else is hidden\n- Click the button again or press Escape to return to the full outline\n- The button highlights when Focus Mode is active\n\n**Properties dialog:**\n- Right-click (desktop) or long-press for the system menu (mobile) on any node and choose 'Properties...'\n- A single dialog shows Type, Color, and Tags for that node\n- Replaces the older separate 'Set Type', 'Set Color', and 'Manage Tags' submenus — fewer menu items, same power\n\n**Larger tap targets (mobile):**\n- The chevron (expand/collapse) and task checkbox now have a 32px hit area for reliable one-tap operation on touch screens. The visible icons stay the same size.\n\n**Note on gestures:** Long-press + still finger enters multi-select. Long-press + movement initiates drag. The system right-click menu still appears for long-presses that the browser interprets as such.");

  // === MULTI-SELECT & BULK OPERATIONS ===
  const multiSelectId = uuidv4();
  const selectingNodesId = uuidv4();
  const bulkOperationsId = uuidv4();

  createNode(nodes, multiSelectId, advancedId, "Multi-Select & Bulk Operations", "Select multiple nodes at once and perform bulk operations for efficient outline management.", []);

  createNode(nodes, selectingNodesId, multiSelectId, "Selecting Multiple Nodes", "Three ways to select multiple nodes:\n\n1. **Cmd/Ctrl + Click**: Toggle individual nodes in/out of selection\n   - Hold Cmd (Mac) or Ctrl (Windows/Linux)\n   - Click any node to add/remove from selection\n   - Selected nodes show blue ring and background\n\n2. **Shift + Click**: Select a range of nodes\n   - Select a node normally first\n   - Hold Shift and click another node\n   - All nodes between them are selected\n\n3. **Esc key**: Clear all selections\n   - Press Esc to deselect all nodes\n   - Returns to single-node selection mode");

  createNode(nodes, bulkOperationsId, multiSelectId, "Bulk Operations Toolbar", "When nodes are selected, a floating toolbar appears at the bottom with bulk actions:\n\n**Tag**: Add a tag to all selected nodes at once\n- Click Tag button\n- Enter tag name\n- Tag is added to all selected nodes\n\n**Color**: Change color of all selected nodes\n- Click Color button\n- Choose from 8 colors\n- All selected nodes get the new color\n\n**Delete**: Remove all selected nodes\n- Click Delete button\n- Confirmation dialog appears\n- All selected nodes and their children are deleted\n\n**Clear**: Deselect all nodes\n- Returns to normal selection mode\n\nThe toolbar shows how many nodes are selected (e.g., \"3 nodes selected\")");

  // === SIDEBAR FEATURES ===
  const sidebarMultiSelectId = uuidv4();
  const sidebarSearchId = uuidv4();

  createNode(nodes, sidebarMultiSelectId, advancedId, "Sidebar Multi-Select & Bulk Delete", "You can select multiple outlines in the sidebar and delete them in one step.\n\n**Selecting outlines (desktop):**\n- **Cmd/Ctrl + Click** an outline to toggle it in/out of selection\n- **Shift + Click** to select a range of outlines between the current and clicked outline\n\n**Selecting outlines (mobile / touch):**\n- **Long-press** any outline in the mobile sidebar sheet to enter select mode (the first long-pressed outline becomes selected)\n- Once in select mode, **tap** other outlines to add or remove them from the selection\n- A bar at the top shows \"X selected\" along with **Cancel** (exit select mode) and **Delete** buttons\n\n**Renaming outlines:**\n- **Desktop:** Right-click an outline (or hover and use the ⋯ menu) and choose Rename\n- **Mobile:** Tap the ⋯ icon on the right of any outline row and choose Rename — an inline text field appears; Enter saves, Escape cancels\n\n**Bulk action bar:**\nWhen outlines are selected, a bar appears showing the count (e.g., \"3 selected\") along with Clear/Cancel and Delete buttons.\n- **Clear / Cancel** deselects all outlines and exits select mode\n- **Delete** opens a single confirmation dialog for the entire batch\n\n**Note:** The delete confirmation setting in Settings applies to both node deletion and outline deletion. If you have turned off confirmations, bulk delete will proceed immediately.");

  createNode(nodes, sidebarSearchId, advancedId, "Sidebar Search", "Quickly find outlines by name using the search field in the sidebar.\n\n**How to use:**\n1. Type in the search field below the Outlines header\n2. The list filters in real time to show only matching outlines\n3. The count updates to show matches vs total (e.g., \"5 / 42\")\n4. Click the X button or clear the text to show all outlines again\n\n**Details:**\n- Search is case-insensitive\n- The User Guide is also filtered by search\n- Available in both the desktop sidebar and the mobile sidebar sheet\n- On mobile, the search clears automatically when you select an outline");

  // === MCP SERVER (API ACCESS) ===
  const mcpId = uuidv4();
  const mcpOverviewId = uuidv4();
  const mcpToolsId = uuidv4();
  const mcpSetupId = uuidv4();

  createNode(nodes, mcpId, rootId, "MCP Server (API Access)", "IdiamPro includes an MCP (Model Context Protocol) server that lets AI assistants like Claude read, write, search, and organize your outlines programmatically.\n\n**What This Means:**\nYou can ask Claude (or any MCP-compatible AI) to work with your outlines directly — list them, search across all your content, create new outlines, add nodes, tag and organize content, and export outlines as Markdown.\n\n**Why It Matters:**\nInstead of manually copying content between AI conversations and your outlines, the AI can read and write directly. This enables powerful workflows like automated research synthesis, bulk organization, and cross-outline analysis.", []);

  createNode(nodes, mcpOverviewId, mcpId, "Available Tools", "The MCP server provides 16 tools organized into categories:\n\n**Read Operations:**\n• list_outlines — See all your outlines with metadata\n• get_outline — Get the full structure of any outline\n• get_node — Retrieve a specific node\n• search_nodes — Full-text search across names and content\n\n**Write Operations:**\n• create_outline — Create a new outline from scratch\n• create_node — Add nodes to any outline\n• update_node — Edit node names and content\n• delete_node — Remove nodes and descendants\n• move_node — Reorganize nodes between parents\n\n**Tags:**\n• add_tag / remove_tag — Manage tags on nodes\n• list_tags — See all tags across outlines\n• filter_by_tags — Find nodes by tag\n\n**Export:**\n• export_outline — Export as Markdown or plain text\n\n**Key Management:**\n• generate_api_key / list_api_keys / revoke_api_key");

  createNode(nodes, mcpToolsId, mcpId, "Example Workflows", "**Research Aggregation:**\n\"Search all my outlines for nodes about machine learning and create a summary outline\"\n\n**Bulk Organization:**\n\"Tag all nodes containing 'TODO' with a 'task' tag across every outline\"\n\n**Content Export:**\n\"Export my Business Plan outline as Markdown so I can share it\"\n\n**Cross-Outline Analysis:**\n\"Find everything I've written about competitors across all outlines\"\n\n**Automated Note-Taking:**\n\"Create a new outline called 'Daily Standup' and add today's agenda items\"");

  createNode(nodes, mcpSetupId, mcpId, "Setup", "**For Claude Desktop:**\n1. The MCP server is included with IdiamPro in the mcp-server/ directory\n2. Build it: open Terminal, navigate to the mcp-server folder, run npm install and npm run build\n3. Add the server to your Claude Desktop configuration file\n4. Restart Claude Desktop\n5. Ask Claude to 'list my outlines' to verify it works\n\n**For Claude Code:**\nAdd the server to your .claude/settings.json MCP servers section.\n\nSee the README in the mcp-server/ folder for detailed configuration instructions.");

  // === NODE NUMBERING ===
  const numberingId = uuidv4();

  createNode(nodes, numberingId, rootId, "Node Numbering", "Each node displays a numeric prefix (like 1.2.3) showing its position in the hierarchy. Prefixes update automatically when you reorganize nodes. The root node has no prefix.");

  // === MOBILE & iOS ===
  const mobileId = uuidv4();
  createNode(nodes, mobileId, rootId, "Mobile & iOS", "On mobile devices and iOS, IdiamPro adapts its interface to work well on smaller screens.\n\n**View Modes:**\nToggle between two view modes using the view switcher:\n\n- **Stacked View**: Shows both the outline pane and content pane side by side (or stacked vertically on narrow screens). Good for quick navigation between nodes.\n- **Content View**: Shows only the content editor in full-screen mode. Ideal for focused writing and editing on mobile.\n\nSwitch between views using the toggle button in the toolbar. Your selected view mode is remembered across sessions.");

  // === PRIVACY & DATA ===
  const privacyDataId = uuidv4();
  const privacyExportId = uuidv4();
  const privacyDeleteId = uuidv4();

  createNode(nodes, privacyDataId, rootId, "Privacy & Data", "IdiamPro stores all your data locally on your device. There is no IdiamPro user account or cloud database today — your outlines, settings, API keys, and AI consent state all live on the machine you're using. The **Privacy & Data** section at the bottom of Settings gives you two GDPR/CCPA-style controls over that local data: export everything as a single archive, or delete everything permanently.\n\nBoth controls only touch IdiamPro-owned data. They do not affect anything else on your device.", []);
  createNode(nodes, privacyExportId, privacyDataId, "Export my data", "Click **Settings → Privacy & Data → Export my data** to generate a single .zip archive containing everything IdiamPro stores on this device:\n\n• `outlines/` — every outline saved as a `.idm` file (JSON format, importable back into IdiamPro)\n• `settings/localStorage.json` — preferences, theme, AI provider, ollama model, and all AI provider API keys you've entered\n• `settings/ai-consent.json` — your current AI data-processing consent state\n• `manifest.json` — metadata about the export (timestamp, platform, counts)\n• `README.txt` — plain-language description of what the archive contains\n\n**How it saves:**\n- **Desktop (Mac/Windows/Linux):** A native save dialog asks where to put the .zip.\n- **Web:** Modern browsers show a save picker; older browsers trigger a regular download.\n- **iOS:** The Share sheet opens so you can save to Files, AirDrop it, email it, or send it to any other app.\n\nThe export works even when AI data consent is revoked — it's a pure local-data operation.\n\n**Heads-up:** Your API keys are exported in plaintext (they're stored that way on your device too). Keep the archive somewhere private.");
  const inputModeId = uuidv4();
  createNode(nodes, inputModeId, rootId, "Input Mode (Type vs. Voice)", "Choose how you want to enter text in the Ask AI command bar (Cmd+K) and the Help chat.\n\nOpen **Settings → Preferences → Input mode** and pick one of three options:\n\n• **Type** (default) — Keyboard only. The mic button still appears so you can dictate any time you want, but it never starts on its own.\n\n• **Voice** — You're planning to dictate. The mic button is there; you tap it when you're ready. Nothing starts automatically.\n\n• **Voice + auto-start** — The mic begins listening the moment you open Ask AI or the Help chat. Ideal for hands-free use. If your browser doesn't support speech recognition (Web Speech API), this option falls back silently to plain typing — nothing breaks.\n\nThe mic icon is always a regular microphone — when listening, the button pulses red so you can see at a glance that it's hot. Click it to stop.");

  createNode(nodes, privacyDeleteId, privacyDataId, "Delete all my data", "Click **Settings → Privacy & Data → Delete all my data…** to permanently erase every piece of IdiamPro data on this device. There is no undo.\n\n**Two-step confirmation:**\n1. The first click opens a warning dialog listing exactly what will be removed and suggesting you export first.\n2. Clicking Continue opens a second dialog that requires you to type **DELETE** in capital letters before the Delete button activates.\n\n**What gets removed:**\n• Every outline (from Electron file storage, File System Access folders, and browser localStorage)\n• All settings and preferences (theme, AI provider, ollama model, sidebar widths, etc.)\n• Every AI provider API key (Gemini, OpenAI, Anthropic, Mistral, Groq)\n• Your AI data-processing consent state\n• The unmerge backup snapshot and conversation history flags\n\n**What does NOT get touched:**\n• Files outside the IdiamPro outlines folder\n• Other apps' data on the same browser origin\n• The outlines folder itself (only the .idm files inside)\n\nAfter the wipe, the app reloads and returns to its fresh-install state.");

  // Admin Dashboard (internal — not user-facing in the normal sense, but the guide explains it)
  const adminDashId = uuidv4();
  createNode(nodes, adminDashId, rootId, "Launch Metrics (admin)", "An internal, restricted page at **/admin/metrics** that shows the launch-week vitals on a single screen: signups this week, activation rate, day-1 and day-7 retention, free-to-paid conversion, AI runs today, and monthly recurring revenue.\n\n**Who sees it:** Only admins. The page checks a local flag (`isAdmin` in browser storage) and shows an access-denied card for everyone else. Real auth-based admin roles will come with the broader auth wire-in.\n\n**Refresh:** Manual — a Refresh button at the top with a \"Last updated ... ago\" timestamp. No background polling, no auto-refresh — you decide when to look.\n\n**Data source today:** All numbers are clearly labelled \"Demo\" until real telemetry (Clerk, RevenueCat, internal events) is wired in. The data layer is structured so each metric can be re-wired independently without changing the page itself.", []);

  // Plans & Tiers
  const plansId = uuidv4();
  createNode(nodes, plansId, rootId, "Plans & Tiers", "IdiamPro has a simple launch tier model with **one rule**: 1 generation = 1 user-initiated AI action (a Help chat answer, a Refresh from Web of any number of nodes, a Translate of any subtree, a Quick Command, etc. — it's the button-press that counts, not the model calls underneath).\n\n**Four tiers:**\n\n**Free trial** — 25 generations total (one-time, not per month). When you run out, add a free API key in Settings (Gemini takes about a minute) or upgrade.\n\n**Free + your own key** — Unlimited. The moment you add ANY provider API key in Settings → AI Service Keys, the counter stops applying. You're paying the provider directly; we don't charge anything.\n\n**Student ($4.99/mo)** — 200 generations per month. Requires a .edu email + honor checkbox at signup.\n\n**Pro ($9.99/mo or $89/yr)** — 1,000 generations per month, plus Pro-only features (podcast generation, image generation), plus priority support. Pro users can also add their own API key to bypass the cap entirely.\n\n**Where to see your usage:** Open **Settings → AI Usage** to see your current tier, generations used and remaining, and when your counter resets (1st of the calendar month, local time). BYOK users see \"Unlimited — using your own API key.\"\n\n**Soft warning at 80%:** A toast appears the first time you cross 80% of your cap, with a friendly heads-up.\n\n**Hard block at 100%:** A polite upgrade dialog appears. Nothing fails silently. You can always add your own key in Settings to keep going for free.\n\n**Local Ollama AI is exempt** — it never counts against your cap (it's running on your own machine).");

  // Onboarding emails — brief mention so users know to expect a welcome + occasional tips
  const onboardingEmailsId = uuidv4();
  createNode(nodes, onboardingEmailsId, rootId, "What we'll email you", "When you sign up for IdiamPro, we send you a short series of emails to help you get the most out of the app:\n\n• A **welcome email** the moment you sign up, with three quick ways to get started.\n• A **day-3 tip** highlighting one underused feature.\n• A **day-7 round-up** with three power-user tips.\n• A **day-14 note** explaining what's behind the Pro tier — no hard sell, just so you know what's there.\n\nThat's it. We don't send marketing newsletters, we don't sell your address, and every email has a one-click **unsubscribe** link in the footer that takes effect immediately. Unsubscribing only stops the onboarding series — the app itself keeps working the same as before.\n\nThe drip emails only fire if you signed in with an email address (the Free trial doesn't require sign-in, so anonymous trial users never get any emails).", []);

  const accountsId = uuidv4();
  createNode(nodes, accountsId, rootId, "Accounts & sign-in", "**IdiamPro is invite-only during beta.** If you signed up successfully, your email was already approved by the IdiamPro team. The signup page checks every new email against the invite list before creating an account — if an email isn't on the list, the page shows a friendly note explaining how to request access (drop a line to hello@2ndbrainware.com) and the account is never created.\n\n**The outliner itself is gated behind a sign-in.** The marketing pages (homepage, /marketing, /pricing, /privacy, /upgrade, /stress-test) stay public so anyone can read about IdiamPro — but to actually use the outliner you create a free account first.\n\n**Sign up:**\n\nFrom the homepage, click **Sign up to try IdiamPro free** in the hero. No credit card required. The page first asks for your email to confirm you're on the invite list; once confirmed, the rest of the Clerk sign-up flow appears. New accounts land directly in their first outline, with the Free trial tier (25 generations).\n\n**Sign in:**\n\nIf you already have an account, click **I already have an account** on the homepage hero, or visit **/signin** directly. After signing in, you go straight to /app — or back to whatever you were trying to open before you got asked to sign in.\n\n**Sign out:**\n\nClick your avatar in the top-right of the app toolbar and pick **Sign out**. You'll land back on the homepage.\n\n**What's private vs public:**\n\n• **Public** (no account needed): homepage, marketing pages, pricing, privacy policy, the /upgrade flow, and /stress-test.\n• **Private** (sign-in required): the /app outliner itself, /admin tools, and any AI endpoint that touches your content (help chat, knowledge chat, podcast generation).\n• **Webhooks** from Clerk and Stripe stay public — they're called by external services and verified by signing secrets, not user auth.", []);

  const upgradeFlowId = uuidv4();
  createNode(nodes, upgradeFlowId, plansId, "Upgrade & Manage Subscription", "**Where to upgrade:**\n\n• **Web / Desktop (Mac, Windows, Linux):** Open the **/upgrade** page (link in any Upgrade dialog, or from Settings → Account → \"See plans\"). Pick Student, Pro Monthly, or Pro Annual ($89/yr — save 25%). Clicking takes you to **Stripe Checkout** — a secure hosted payment page that supports cards, Apple Pay, and Google Pay automatically. Your new tier is live the moment Stripe confirms the charge.\n\n• **iPhone / iPad:** Subscriptions go through Apple's In-App Purchase (App Store guideline 3.1.1). The same upgrade buttons open Apple's purchase sheet instead of Stripe. Apple handles the receipt and family sharing. RevenueCat keeps the entitlement in sync across platforms — pay on web, your iPhone unlocks too.\n\n**Manage your subscription:**\n\nOpen **Settings → Account → Manage Subscription**. On web/desktop this opens **Stripe's hosted Customer Portal** where you can cancel, change plan (e.g. Monthly → Annual), update your card, or view past invoices. On iOS it routes to Apple's Subscriptions screen (Settings → Apple ID → Subscriptions).\n\n**Why both?** RevenueCat is the single source of truth for \"which tier do you have right now?\" — regardless of which payment system handled the charge. That's why your subscription works seamlessly across web, Mac, and iPhone.\n\n**Cancel anytime, no questions asked.** When you cancel, you keep access until the end of your current billing period.");

  // Set types and prefixes
  Object.keys(nodes).forEach(nodeId => {
    const node = nodes[nodeId];
    if (node.childrenIds.length > 0) {
      node.type = 'chapter';
    }
    node.prefix = calculateNodePrefix(nodes, nodeId);
  });

  nodes[rootId].type = 'root';
  nodes[rootId].prefix = '';

  return { rootNodeId: rootId, nodes };
}

export function getInitialGuide(): Outline {
  const { rootNodeId, nodes } = createGuideNodes();
  return {
    id: 'guide',
    name: 'IdiamPro User Guide',
    rootNodeId,
    nodes,
    isGuide: true,
  };
}
