'use client';

import type { Outline, OutlineNode } from '@/types';
import type { ExportOptions, ExportResult } from '../types';
import { BaseExporter } from '../base-exporter';

/**
 * Export outline to FreeMind (.mm) XML format
 * Standard mind map format supported by many mind mapping tools
 */
export class FreeMindExporter extends BaseExporter {
  formatId = 'freemind';
  mimeType = 'application/x-freemind';
  extension = '.mm';

  async convert(
    outline: Outline,
    rootNodeId?: string,
    options?: ExportOptions
  ): Promise<ExportResult> {
    const root = rootNodeId || outline.rootNodeId;
    const nodes = outline.nodes;
    const includeContent = options?.includeContent ?? true;
    const maxDepth = options?.maxDepth;

    const mapContent = this.buildNode(nodes, root, includeContent, maxDepth, 0);

    const mm = `<map version="1.0.1">
<!-- Generated by IdiamPro -->
${mapContent}
</map>`;

    return {
      data: mm,
      filename: this.getSuggestedFilename(outline, rootNodeId),
      mimeType: this.mimeType,
    };
  }

  private buildNode(
    nodes: Record<string, OutlineNode>,
    nodeId: string,
    includeContent: boolean,
    maxDepth: number | undefined,
    depth: number
  ): string {
    if (maxDepth !== undefined && depth > maxDepth) return '';

    const node = nodes[nodeId];
    if (!node) return '';

    const indent = '  '.repeat(depth + 1);
    const text = this.escapeXml(node.name);
    const hasChildren = node.childrenIds && node.childrenIds.length > 0;

    let xml = `${indent}<node TEXT="${text}"`;

    // Add position hint for first-level nodes (alternate left/right)
    if (depth === 1) {
      // FreeMind uses POSITION for layout direction
    }

    if (!hasChildren && !(includeContent && node.content)) {
      xml += '/>\n';
      return xml;
    }

    xml += '>\n';

    // Add content as richcontent note
    if (includeContent && node.content) {
      const content = this.stripHtml(node.content);
      if (content) {
        xml += `${indent}  <richcontent TYPE="NOTE"><html><head></head><body><p>${this.escapeHtml(content)}</p></body></html></richcontent>\n`;
      }
    }

    // Children
    if (hasChildren) {
      for (const childId of node.childrenIds!) {
        xml += this.buildNode(nodes, childId, includeContent, maxDepth, depth + 1);
      }
    }

    xml += `${indent}</node>\n`;
    return xml;
  }
}
